In [1]:
import numpy as np

In [2]:
# 2D array
a = np.zeros((3, 3))
# All rows to 2
a[:] = 2
print(a)
print(a.dtype)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
float64


In [3]:
# Array 3x3
b = np.arange(1, 10).reshape((3, 3))
print(b)
print(b.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64


In [4]:
# Convierto a a int
a = np.zeros((3, 3), dtype=np.int64)
a[:] = 2
print(a)
print(a.dtype)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
int64


In [5]:
# metodo .fill() fills array with values
a = np.zeros((3, 3), dtype=np.int64)
a[:] = 2
a.fill(8)
print("Array A\n", a)

Array A
 [[8 8 8]
 [8 8 8]
 [8 8 8]]


In [6]:
# Assignement operator
a = np.zeros((3, 3), dtype=np.int64)
a[:] = 2
a.fill(8)
a += 3
print("Array A\n", a)

Array A
 [[11 11 11]
 [11 11 11]
 [11 11 11]]


In [7]:
a = np.zeros((3, 3), dtype=np.int64)
a[:] = 2
a.fill(8)
a /= 3  # Problema al dividir int y resultar un float
print("Array A\n", a)

UFuncTypeError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [8]:
# Problema solucionado quitando el hardcoding de dtype
a = np.zeros((3, 3))
a[:] = 2
a.fill(8)
a /= 3
print("Array A\n", a)

Array A
 [[2.66666667 2.66666667 2.66666667]
 [2.66666667 2.66666667 2.66666667]
 [2.66666667 2.66666667 2.66666667]]


In [9]:
# Metodos aritmeticos
a = np.zeros((3, 3), dtype=np.int64)
a.fill(2)
# Suma todo el array
array_sum = a.sum()
print("Array A\n", a)
print(array_sum)

Array A
 [[2 2 2]
 [2 2 2]
 [2 2 2]]
18


In [10]:
# Suma cada columna (0 = col) (1 = fila)
array_sum = b.sum(axis=0)
print("Array B\n", b, "\n")
print(array_sum)

Array B
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

[12 15 18]


In [11]:
# Producto. Multiply all items by one another
array_product = a.prod()
print("Array A\n", a)
print(array_product)  # 2^9

Array A
 [[2 2 2]
 [2 2 2]
 [2 2 2]]
512


In [12]:
# Media
array_average = b.mean()
print("Array B\n", b, "\n")
print(array_average)

Array B
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

5.0


In [13]:
# Maximum and minimum values
b_max, b_min = b.max(), b.min()
print("Array B\n", b, "\n")
print(b_max, ",", b_min)

Array B
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

9 , 1


In [14]:
# Index of Maximum and minimum
b_max_index, b_min_index = b.argmax(), b.argmin()
print(b_max_index, ",", b_min_index)

8 , 0


In [15]:
# Peak to peak (max - min)
b_peak_to_peak = np.ptp(b)
print(b_peak_to_peak)

8


In [16]:
# Flatten arrays. Size attr
array_flat = b.reshape(b.size)  # Total items
print(array_flat)

[1 2 3 4 5 6 7 8 9]


In [17]:
array_flat = b.flatten()  # copies the original array
print(array_flat)

[1 2 3 4 5 6 7 8 9]


In [18]:
array_flat = b.ravel()  # Creats a view of the original
print(array_flat)

[1 2 3 4 5 6 7 8 9]


In [19]:
# Repeat values/arrays
arrays_repeat = np.repeat(255, 3)
print(arrays_repeat)

[255 255 255]


In [20]:
# All values in b repeats 3 times, .repeat()
arrays_repeat = np.repeat(b, 3)
print(arrays_repeat)

[1 1 1 2 2 2 3 3 3 4 4 4 5 5 5 6 6 6 7 7 7 8 8 8 9 9 9]


In [21]:
arrays_repeat_columns = np.repeat(b, 3, axis=0)
print("Array B\n", b, "\n")
print(arrays_repeat_columns)

Array B
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]
 [7 8 9]
 [7 8 9]
 [7 8 9]]


In [22]:
arrays_repeat_rows = np.repeat(b, 3, axis=1)
print("Array B\n", b, "\n")
print(arrays_repeat_rows)

Array B
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]
 [7 7 7 8 8 8 9 9 9]]


In [23]:
arrays_repeat_rows = np.repeat(b, 3, axis=1)
# Reverse the result of repeat,  np.unique()
array_unique = np.unique(arrays_repeat_rows, axis=1)
print("Array B\n", b, "\n")
print(arrays_repeat_rows, "\n")
print(array_unique)

Array B
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]
 [7 7 7 8 8 8 9 9 9]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
# Diagonal function.  Atrapa la diagonal en el array
arrays_repeat_rows = np.repeat(b, 3, axis=1)
array_unique = np.unique(arrays_repeat_rows, axis=1)
array_diagonal = np.diagonal(b)
print(array_unique, "\n")
print(array_diagonal)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 5 9]


In [27]:
# offset parameter.
# 1 Selecciona la diagonal siguiente, 0 la anterior
arrays_repeat_rows = np.repeat(b, 3, axis=1)
array_unique = np.unique(arrays_repeat_rows, axis=1)
array_diagonal = np.diagonal(b, offset=1)
print(array_unique, "\n")
print(array_diagonal)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[2 6]


In [29]:
# Conversion and storage
my_list = b.tolist()
print("b is ", type(b))
print("My list is", type(my_list))

# covertir a txt
b.tofile("my_array.txt", sep=",")

b is  <class 'numpy.ndarray'>
My list is <class 'list'>


In [32]:
# Transposition. 3 Maneras
# Swaping axis, or Flipping rows with columns
array_swapped = np.swapaxes(b, 0, 1)  # obj, axis0, axis1
print("Array B\n", b, "\n")
print(array_swapped)

Array B
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [33]:
array_swapped = np.swapaxes(b, 0, 1)
array_swapped = b.transpose(1, 0)  # axis 1, axis 0
print("Array B\n", b, "\n")
print(array_swapped)

Array B
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [34]:
array_swapped = np.swapaxes(b, 0, 1)
array_swapped = b.transpose(1, 0)
array_swapped = b.T
print("Array B\n", b, "\n")
print(array_swapped)

Array B
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [40]:
# Operation on 2 matrices (2 arrays)
simple_ops = (a + b - 2*a) / 4
print("Array A\n", a, "\n")
print("Array B\n", b, "\n")
print(simple_ops)

Array A
 [[2 2 2]
 [2 2 2]
 [2 2 2]] 

Array B
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]]


In [41]:
# Operation on 2 matrices (2 arrays)
simple_ops = (a + b - 2*a) / 4
modulo = b % a
print("Array A\n", a, "\n")
print("Array B\n", b, "\n")
print(modulo)

Array A
 [[2 2 2]
 [2 2 2]
 [2 2 2]] 

Array B
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [44]:
# Operation on 2 matrices (2 arrays)
simple_ops = (a + b - 2*a) / 4
modulo = b % a
floor_division = b // a  # Integers
floor_division = np.floor(b/a)  # Floats
print("Array A\n", a, "\n")
print("Array B\n", b, "\n")
print(floor_division)

Array A
 [[2 2 2]
 [2 2 2]
 [2 2 2]] 

Array B
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[0. 1. 1.]
 [2. 2. 3.]
 [3. 4. 4.]]


In [45]:
# Matrix multiplication (manual)
matrix_multiply = np.matmul(a, b)
print("Array A\n", a, "\n")
print("Array B\n", b, "\n")
print(a*b)  # Elemento * elemento en filas (i*i)

Array A
 [[2 2 2]
 [2 2 2]
 [2 2 2]] 

Array B
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [49]:
# Matrix multiplication(np.matmul())
matrix_multiply = np.matmul(a, b)
print("Array A\n", a, "\n")
print("Array B\n", b, "\n")
print(matrix_multiply)
# Elemento en fila * elemento col. (i*j)
# A(i)*B(j) + A(i)*B(j) + A(i)*B(j) = 24

Array A
 [[2 2 2]
 [2 2 2]
 [2 2 2]] 

Array B
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[24 30 36]
 [24 30 36]
 [24 30 36]]


In [50]:
# Matrix multiplication(.dot)
matrix_multiply = a.dot(b)
print("Array A\n", a, "\n")
print("Array B\n", b, "\n")
print(matrix_multiply)
# Elemento en fila * elemento col. (i*j)
# A(i)*B(j) + A(i)*B(j) + A(i)*B(j) = 24

Array A
 [[2 2 2]
 [2 2 2]
 [2 2 2]] 

Array B
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[24 30 36]
 [24 30 36]
 [24 30 36]]


In [51]:
# Matrix multiplication (@)
matrix_multiply = a @ b
print("Array A\n", a, "\n")
print("Array B\n", b, "\n")
print(matrix_multiply)
# Elemento en fila * elemento col. (i*j)
# A(i)*B(j) + A(i)*B(j) + A(i)*B(j) = 24

Array A
 [[2 2 2]
 [2 2 2]
 [2 2 2]] 

Array B
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[24 30 36]
 [24 30 36]
 [24 30 36]]
